import { Geist, Geist_Mono, Inter, Outfit, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
});

const jakarta = Plus_Jakarta_Sans({
  
  subsets: ["latin"]
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jakarta.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
